### ISSUE TITLE
Hỏi về cách train model

### ISSUE THREAD

**Issue by DungLeMTA** [mailong25/bert-vietnamese-question-answering#4]
A Mai Long ơi, em hiện cũng đang làm về 1 đề tài Q-A luật giao thông, project của a rất hay và e muốn học theo, nhưng mà e xem thấy bộ dataset của a khác với dataset gốc tiếng Anh ạ. A có thể share file train của a được không ạ, em cảm ơn a nhiều 👍

**Comment by mailong25** [comment]
A không còn giữ file train.
E tham khảo https://github.com/huggingface/transformers/tree/master/examples/question-answering nhé

**Comment by DungLeMTA** [comment]
vâng e cám ơn a ạ
